### ISSUE TITLE
Add Diff support for Bitbucket

### ISSUE THREAD

**Issue by pastelsky** [rhysd/git-brws#17]
It appears that Bitbucket does support diff between two commits /tags/branches using the following URL format –

```
https://bitbucket.org/<owner>/<repoName>.git/branches/compare/<commitHash1>..<commitHash2>#diff
```

**Comment by rhysd** [comment]
Thank you for letting me know this.

**Comment by rhysd** [comment]
The URL seems not working. For example, I tried with Tortoise HG repository:

https://bitbucket.org/tortoisehg/thg/branches/compare/a6b614f9bb0e5a6cbded3fa462f99c6dee4e2caa..d3966d0b6bd834ab8e8cc17277219eea0bbf2fa7#diff

But it says 'There are no changes.' URL without `/branches/` also does not work:

https://bitbucket.org/tortoisehg/thg/compare/a6b614f9bb0e5a6cbded3fa462f99c6dee4e2caa..d3966d0b6bd834ab8e8cc17277219eea0bbf2fa7#diff

As per [answers in this question](https://community.atlassian.com/t5/Bitbucket-questions/BitBucket-4-14-diff-between-any-two-commits/qaq-p/632974), the URL does not work when both hash1 and hash2 are in the same branch.
