### ISSUE TITLE
Invalid port number when user name starts with numbers

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [rhysd/git-brws#24]
I got the following error when executing on Windows 10. Any ideas?

```
C:\Users\admin\AppData\Local\nvim>git-brws
Error: Broken URL 'ssh://git@github.com:0x7FFFFFFFFFFFFFFF/neovim_config.git': invalid port number

C:\Users\admin\AppData\Local\nvim>cat .git/config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = git@github.com:0x7FFFFFFFFFFFFFFF/neovim_config.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[credential]
        helper = store

C:\Users\admin\AppData\Local\nvim>
```

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Btw, this repository is in good state and I can push or pull without any issue.

**Comment by rhysd** [comment]
Thanks for the report. Is what you tried as follows?

```
git clone git@github.com:0x7FFFFFFFFFFFFFFF/neovim_config.git
cd neovim_config/
git brws
```

And how did you prepare `git-brws` binary? (I guess you downloaded it from releases page)

At first I want to reproduce this on Windows.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I tried the commands you provided.

```
C:\my_projects>git clone git@github.com:0x7FFFFFFFFFFFFFFF/neovim_config.git
Cloning into 'neovim_config'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (41/41), done.
Receiving objects:  43a 24), reused 45 (delta 12), pack-reused 0R
Receiving objects: 100% (57/57), 42.26 KiB | 10.00 KiB/s, done.
Resolving deltas: 100% (24/24), done.

C:\my_projects>cd neovim_config

C:\my_projects\neovim_config>git-brws
Error: Broken URL 'ssh://git@github.com:0x7FFFFFFFFFFFFFFF/neovim_config.git': invalid port number

C:\my_projects\neovim_config>git-brws --version
0.11.9

C:\my_projects\neovim_config>
```

Yes, I grabbed the git-brws from the release page and put it in PATH. Btw, my testing repo is a private one. Does this matter?

**Comment by rhysd** [comment]
I see. https://github.com/0x7FFFFFFFFFFFFFFF/neovim_config seems a private repository. I'll try the commands with my private repository on Windows tomorrow.

**Comment by rhysd** [comment]
It may be related to that your name starts with number. I'll check it tomorrow.

**Comment by rhysd** [comment]
I could reproduce this. It is not depending on platform.

1. `git clone https://github.com/rhysd/git-brws.git && cd git-brws`
2. Replace `https://github.com/rhysd/git-brws.git` with `git@github.com:0x7FFFFFFFFFFFFFFF/neovim_config.git` in `.git/config`
3. Run `git brws`

I think this is a bug when converting `git@` abbreviated URL to `ssh://` URL for parsing it correctly.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thank you for the quick fix!

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I confirmed it works now. Thanks again!

**Comment by rhysd** [comment]
FYI: v0.11.10 was released https://github.com/rhysd/git-brws/releases/tag/v0.11.10
