### ISSUE TITLE
Upgrade to tokio v1

### ISSUE THREAD

**Issue by rhysd** [rhysd/git-brws#29]
Blocked by https://github.com/seanmonstar/reqwest/issues/1060.

I'm working on this at [`tokio-0.3` branch](https://github.com/rhysd/git-brws/tree/tokio-0.3).

**Comment by felipesere** [comment]
Just dropping by to say that reqwest is on tokio 1.0 🎉

**Comment by rhysd** [comment]
Thank you for letting me know. I'll try new version of reqwest.
