### ISSUE TITLE
git brws --help doesn't work

### ISSUE THREAD

**Issue by wtsnjp** [rhysd/git-brws#8]
The short option `-h` does work fine and print the help text:

```shell
$ git brws -h
Usage: git brws [Options] {Args}

[...]

    -h, --help          Print this help
    -v, --version       Show version
```

According to the above help, the long version of the option (`--help`) is also valid and will show the same help text. However, this doesn't seem working in such a way.

```shell
$ git brws --help
No manual entry for git-brws
```

Followings are some environmental information:

```shell
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G4015

$ git --version
git version 2.20.1
hub version 2.7.0

$ git brws --version
0.8.1
```

**Comment by rhysd** [comment]
Actually this behavior is intended, but I agree that it is not so expected.

When running

```
git subcmd --help
```

the `--help` is **not** handled by `git-subcmd`, but by `git` itself. `git` searches a man manual for `git-subcmd`. `git-subcmd` cannot override this behavior.

```
git-brws --help
```

would work fine.

The perfect (and only I guess) fix is providing a man manual (`git-brws.1`) but I'm not familiar with the format and I don't want to bother users by requiring to install the man manual.

**Comment by wtsnjp** [comment]
> the --help is **not** handled by git-subcmd, but by git itself.

In this case I can see that it is difficult to solve this issue inside `git-brws`.

> The perfect (and only I guess) fix is providing a man manual (`git-brws.1`) but I'm not familiar with the format and I don't want to bother users by requiring to install the man manual.

I can understand your concern and I also think creating a man entry for this project is somehow overkilling. (By the way, JFYR, it is not necessary to know about the format (roff) to write a man page because there are useful converters, e.g., [ronn](https://github.com/rtomayko/ronn).)

Anyway, I personally don't have any trouble with this issue since I know `git brws -h` is workable. If this behavior is intentional as you said, I have nothing to add... I wish I had a better idea to solve 😢

**Comment by rhysd** [comment]
> I can understand your concern and I also think creating a man entry for this project is somehow overkilling. (By the way, JFYR, it is not necessary to know about the format (roff) to write a man page because there are useful converters, e.g., ronn.)

I did not know `ronn`. Thank you for letting me know. I think I should try.

> Anyway, I personally don't have any trouble with this issue since I know git brws -h is workable. If this behavior is intentional as you said, I have nothing to add... I wish I had a better idea to solve 😢

Yeah... what we can do which I was able to come up with is removing `--help` from flags.

**Comment by rhysd** [comment]
I added `git-brws.1` at dc957bf and added note in 'Installation' section in README. Thank you for reporting this.

**Comment by rhysd** [comment]
Note: I setup Homebrew formula which put `git-brws.1` properly. When installing `git-brws` via Homebrew, `git brws --help` should work.

https://github.com/rhysd/git-brws#installation
